title: Tmntduke
description: 爱读书 爱音乐 爱编程
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

# URL
## If your site is put in a subdirectory, set tmntduke.github.io as 'tmntduke.com' and root as '/child/'
